// packages/react-demo/src/demo-components/UsageFull.tsx
import React from 'react';
import { Icon } from '@iconify/react';

export function FullUsageDemo() {
	return (
		<section className="icon-24">
			<h1>Usage (full module)</h1>
			<div>
				Icon referenced by name: <Icon icon="mdi:home" />
			</div>
			<div className="alert">
				<Icon icon="mdi-light:alert" />
				Important notice with alert icon!
			</div>
		</section>
	);
}

// packages/svelte-demo/src/demo-components/UsageFull.svelte
<script>
	import Icon from '@iconify/svelte';
</script>

<section class="icon-24">
    <h1>Usage  (full module)</h1>
    <div>
        Icon referenced by name: <Icon icon="mdi:home" />
    </div>
    <div class="alert">
        <Icon icon="mdi-light:alert" />
        Important notice with alert icon!
    </div>
</section>
